import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[bell]
 animation = "EaseOutExpo"
 color = "#ffffff"
 duration = 5

 [colors.primary]
 background = "#1b1b1b"
 foreground = "#ebdbb2"

 [font]
 size = 16
 [font.normal]
 family = "JetBrainsMono Nerd Font"
 style = "Medium"

 [[hints.enabled]]
 command = "/home/dimfatal/.nix-profile/bin/mimeo"
 post_processing = true
 regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

 [hints.enabled.mouse]
 enabled = true

 [[keyboard.bindings]]
 action = "SearchBackward"
 key = 53
 mode = "Vi"
 mods = "Shift"

 [selection]
 save_to_clipboard = true

 [shell]
 program = "/home/dimfatal/.nix-profile/bin/fish"

 [window]
 decorations = "full"
 opacity = 0.98

 [window.padding]
 x = 5
 y = 5